
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %> 
  host: icebreak_db_1
  port: 5432

development:
  <<: *default
  database: loveicebreak_development

  
test:
  <<: *default
  database: loveicebreak_test


production:
  <<: *default
  database: loveicebreak_production
  username: loveicebreak
  password: <%= ENV['LOVEICEBREAK_DATABASE_PASSWORD'] %>
